version: 2
jobs:
  build:
    working_directory: ~/nodejs-prometheus-wrapper
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install && yarn add --peer 'prom-client@^7.2.0'
      - run:
          name: Run tests
          command: yarn test
